version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quarkus:
    image: quarkus/jpa-jvm
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/yourdatabase
      QUARKUS_DATASOURCE_USERNAME: yourusername
      QUARKUS_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: